export const logoMAsset = '/img/logo_m.svg'
export const logoMWhiteAsset = '/img/logo_m_blanco.svg'
export const loomaAsset = '/img/logo_looma.svg'
export const defaultAvatarAsset = '/img/default-avatar.png'
export const avatarMAsset = '/img/avatar-m.png'
export { default as settingsIconAsset } from './icon_settings.svg'
export { default as settingsIconWhiteAsset } from './icon_settings.svg'
export { default as notificationIconAsset } from './icon_notification.svg'
export { default as notificationIconWhiteAsset } from './icon_notification.svg'
export { default as deleteIconNAsset } from './icon_delete_n.svg'
